-- APIJSON H2数据库初始化脚本

-- 用户基本信息表
CREATE TABLE IF NOT EXISTS User (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL COMMENT '用户名',
  tag VARCHAR(45) COMMENT '标签',
  head VARCHAR(300) COMMENT '头像url',
  contactIdList VARCHAR(1024) COMMENT '联系人id列表',
  pictureList VARCHAR(1024) COMMENT '照片列表',
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id)
);

-- 用户隐私信息表
CREATE TABLE IF NOT EXISTS Privacy (
  id BIGINT NOT NULL,
  certified TINYINT(1) DEFAULT 0 COMMENT '是否认证',
  phone VARCHAR(20) COMMENT '手机号',
  balance DECIMAL(10,2) DEFAULT 0 COMMENT '余额',
  _password VARCHAR(128) COMMENT '登录密码',
  _payPassword VARCHAR(32) COMMENT '支付密码',
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id)
);

-- 验证码表
CREATE TABLE IF NOT EXISTS Verify (
  id BIGINT NOT NULL AUTO_INCREMENT,
  type INT NOT NULL DEFAULT 0 COMMENT '类型: 0-登录 1-注册 2-密码 3-支付密码 4-重载',
  phone VARCHAR(20) NOT NULL COMMENT '手机号',
  verify VARCHAR(8) NOT NULL COMMENT '验证码',
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id)
);

-- 访问权限配置表
CREATE TABLE IF NOT EXISTS Access (
  id BIGINT NOT NULL AUTO_INCREMENT,
  debug TINYINT(1) DEFAULT 0 COMMENT '是否调试模式',
  name VARCHAR(50) NOT NULL COMMENT '实际表名',
  alias VARCHAR(20) COMMENT '外部调用的表别名',
  get TEXT COMMENT 'GET访问权限',
  head TEXT COMMENT 'HEAD访问权限',
  gets TEXT COMMENT 'GETS访问权限',
  heads TEXT COMMENT 'HEADS访问权限',
  post TEXT COMMENT 'POST访问权限',
  put TEXT COMMENT 'PUT访问权限',
  delete TEXT COMMENT 'DELETE访问权限',
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id)
);

-- 请求校验配置表
CREATE TABLE IF NOT EXISTS Request (
  id BIGINT NOT NULL AUTO_INCREMENT,
  debug TINYINT(1) DEFAULT 0 COMMENT '是否调试模式',  
  version TINYINT NOT NULL DEFAULT 1 COMMENT '接口版本号',
  method VARCHAR(10) NOT NULL DEFAULT 'GETS' COMMENT '请求方法',
  tag VARCHAR(20) NOT NULL COMMENT '标签',
  structure TEXT NOT NULL COMMENT '请求结构',
  detail TEXT COMMENT '详细说明',
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id)
);

-- 函数配置表
CREATE TABLE IF NOT EXISTS Function (
  id BIGINT NOT NULL AUTO_INCREMENT,
  debug TINYINT(1) DEFAULT 0 COMMENT '是否调试模式',
  userId BIGINT COMMENT '用户id',
  name VARCHAR(30) NOT NULL COMMENT '方法名',
  arguments VARCHAR(1024) COMMENT '参数列表',
  demo TEXT NOT NULL COMMENT '可用的demo',
  detail TEXT COMMENT '详细说明',
  type VARCHAR(50) NOT NULL DEFAULT 'Object' COMMENT '返回类型',
  version TINYINT NOT NULL DEFAULT 0 COMMENT '版本号',
  tag VARCHAR(20) COMMENT '标签',
  methods VARCHAR(255) COMMENT '允许的请求方法',
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id)
);

-- 为了兼容，保留原有的apijson_user表
CREATE TABLE IF NOT EXISTS apijson_user (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL COMMENT '用户名称',
  phone VARCHAR(20) NOT NULL COMMENT '手机号',
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id)
);